version: '3.1'
services:
  web:
    build:
            context: .
            dockerfile: Dockerfile
    container_name: odoo_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    labels:
      - "traefik.http.routers.whoami.rule=Host(`odoo.ridha-bouazizi.live`)"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ./certbot/www:/var/www/certbot/:ro
  db:
    container_name: odoo_db
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  reverse-proxy:
      # The official v2 Traefik docker image
      image: traefik:v2.6
      # Enables the web UI and tells Traefik to listen to docker
      command: --api.insecure=true --providers.docker
      ports:
      # The HTTP port
        - "80:80"
      # The Web UI (enabled by --api.insecure=true)
        - "8081:8080"
      volumes:
      # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
          #  certbot:
          #image: certbot/certbot:latest
          #volumes:
          #- ./certbot/www/:/var/www/certbot/:rw
          #- ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  odoo-db-data:
  odoo-web-data:
