version: '3.1'
services:
  web:
    build:
            context: .
            dockerfile: Dockerfile
    container_name: odoo_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
  db:
    container_name: odoo_db
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-db-data:
  odoo-web-data:
